### ISSUE TITLE
Deleted Chronos timers popping (on separate node?)

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/chronos#175] opened 2015-09-24 10:28 UTC
Essentially, I've seen a Chronos timer be deleted on one node and then pop on another node. My suspicion is that there's a problem propagating the delete through the Chronos cluster.

There are logs available. See Session-Id ralf-1.vmware.obu-enfield.test;1441718664;208594.

See referenced issue for more information.

**Comment by graemerobertson** [comment] 2015-09-24 10:28
See https://github.com/Metaswitch/cedar/issues/68

**Comment by eleanor-merry** [comment] 2015-11-17 12:28
Closing as I can't reproduce this issue with the latest code (and there are a number of changes that have recently gone in that could have reasonably fixed this)

**Closed by eleanor-merry** 2015-11-17 12:28 UTC
Labels: bug, medium-priority
